# Dockerfile do backend

# Usar a imagem oficial do Node.js
FROM node:18

# Diretório de trabalho no contêiner
WORKDIR /app

# Copiar arquivos de dependências
COPY package*.json ./

# Instalar dependências
RUN npm install

# Copiar o restante do código
COPY ./src ./

# Expor a porta usada pelo backend
EXPOSE 3000

# Comando para rodar o backend
CMD ["node", "app.js"]
