version: '3.8'

services:
  backend:
    build: ./src
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  frontend:
    build:
      context: ./Interface/vite-project
      dockerfile: Dockerfile
    volumes:
      - ./Interface/vite-project/dist:/app/dist 
    networks:
      - app-network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Interface/vite-project/nginx/default.conf:/etc/nginx/conf.d/default.conf  
      - ./ssl/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt             
      - ./ssl/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
      - ./ssl/dhparam.pem:/etc/nginx/ssl/dhparam.pem
      - ./Interface/vite-project/dist:/usr/share/nginx/html 
    depends_on:
      - frontend
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge