version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" # Porta do backend
    volumes:
      - ./src:/app/src # Monta o código do backend
      - /app/node_modules # Evita conflitos com dependências nativas
    env_file:
      - ./.env
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80" # Porta pública
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Arquivo de configuração Nginx
    depends_on:
      - backend # O Nginx espera o backend iniciar
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
